version: "3.8"

services:
  db:
    image: postgres:15
    container_name: my_project_db
    environment:
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student123
      POSTGRES_DB: projectdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d:ro
    restart: unless-stopped

volumes:
  db_data:
